const fs = require("fs");
const path = require("path");

const files = fs.readdirSync(process.cwd())
  .filter(f => f.endsWith(".html") && f !== "index.html")
  .sort();

const links = files
  .map(f => `<li data-name="${f.toLowerCase()}"><a href="${f}">${f}</a></li>`)
  .join("\n");

const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Index</title>
<style>
  body {
    font-family: system-ui, sans-serif;
    background: #f7f7f7;
    padding: 24px;
    max-width: 900px;
    margin: 0 auto;
  }

  h1 {
    font-size: 1.25rem;
    margin-bottom: 16px;
  }

  .controls {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
    margin-bottom: 16px;
    align-items: center;
  }

  input[type=text] {
    flex: 1;
    padding: 10px 12px;
    font-size: 14px;
  }

  ul {
    list-style: none;
    padding: 0;
    margin: 0;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
    gap: 10px;
  }

  li {
    background: #fff;
    border-radius: 6px;
    border: 1px solid #ddd;
    padding: 10px 12px;
    transition: box-shadow 0.15s ease, transform 0.1s ease;
  }

  li:hover {
    box-shadow: 0 4px 12px rgba(0,0,0,0.08);
    transform: translateY(-1px);
  }

  a {
    text-decoration: none;
    color: #111;
    font-size: 14px;
    word-break: break-all;
  }

  .note {
    font-size: 12px;
    color: #555;
    margin: 8px auto 0;
  }
</style>
</head>
<body>
<h1>Available Tools</h1>

<div class="controls">
  <input id="search" type="text" placeholder="Search pages...">
</div>

<ul id="list">
${links}
</ul>

<p class="note">A collection of useful HTML tools generated by JiBT brain.</p>

<script>
  const input = document.getElementById("search");
  const items = Array.from(document.querySelectorAll("li"));

  input.addEventListener("input", () => {
    const q = input.value.toLowerCase();
    items.forEach(li => {
      li.style.display = li.dataset.name.includes(q) ? "" : "none";
    });
  });
</script>

</body>
</html>
`;

fs.writeFileSync("index.html", html);
console.log("Generated index.html");
console.log("Linked files:", files);
